- name: Generate public/images/_index.json
  run: |
    node - <<'NODE'
    const fs = require('fs');
    const path = require('path');

    const ROOT = 'public';
    const DIR  = 'public/images';
    const exts = new Set(['.jpg','.jpeg','.png','.gif','.webp','.avif','.svg']);

    function walk(p){
      let out=[];
      for(const e of fs.readdirSync(p,{withFileTypes:true})){
        const full = path.join(p,e.name);
        if(e.isDirectory()) out = out.concat(walk(full));
        else if(exts.has(path.extname(e.name).toLowerCase())){
          const rel = path.relative(ROOT, full);             // public からの相対
          const web = rel.split(path.sep).join('/');         // URL向けに '/' に統一
          out.push(web);                                     // => 'images/...'
        }
      }
      return out;
    }

    const files = fs.existsSync(DIR) ? walk(DIR) : [];
    const list  = files.sort().map(src => ({ src, title: path.parse(src).name }));
    fs.mkdirSync('public/images', { recursive:true });
    fs.writeFileSync('public/images/_index.json', JSON.stringify(list, null, 2));
    console.log('Wrote', list.length, 'entries');
    NODE
